// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package replication

import (
	mock "github.com/stretchr/testify/mock"
	"github.io/cbuschka/go-legible-tests/domain/product"
)

// newMockmetricsSender creates a new instance of mockmetricsSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockmetricsSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockmetricsSender {
	mock := &mockmetricsSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockmetricsSender is an autogenerated mock type for the metricsSender type
type mockmetricsSender struct {
	mock.Mock
}

type mockmetricsSender_Expecter struct {
	mock *mock.Mock
}

func (_m *mockmetricsSender) EXPECT() *mockmetricsSender_Expecter {
	return &mockmetricsSender_Expecter{mock: &_m.Mock}
}

// ReportFailure provides a mock function for the type mockmetricsSender
func (_mock *mockmetricsSender) ReportFailure(err error) {
	_mock.Called(err)
	return
}

// mockmetricsSender_ReportFailure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportFailure'
type mockmetricsSender_ReportFailure_Call struct {
	*mock.Call
}

// ReportFailure is a helper method to define mock.On call
//   - err error
func (_e *mockmetricsSender_Expecter) ReportFailure(err interface{}) *mockmetricsSender_ReportFailure_Call {
	return &mockmetricsSender_ReportFailure_Call{Call: _e.mock.On("ReportFailure", err)}
}

func (_c *mockmetricsSender_ReportFailure_Call) Run(run func(err error)) *mockmetricsSender_ReportFailure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockmetricsSender_ReportFailure_Call) Return() *mockmetricsSender_ReportFailure_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockmetricsSender_ReportFailure_Call) RunAndReturn(run func(err error)) *mockmetricsSender_ReportFailure_Call {
	_c.Run(run)
	return _c
}

// ReportSuccess provides a mock function for the type mockmetricsSender
func (_mock *mockmetricsSender) ReportSuccess(count int) {
	_mock.Called(count)
	return
}

// mockmetricsSender_ReportSuccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportSuccess'
type mockmetricsSender_ReportSuccess_Call struct {
	*mock.Call
}

// ReportSuccess is a helper method to define mock.On call
//   - count int
func (_e *mockmetricsSender_Expecter) ReportSuccess(count interface{}) *mockmetricsSender_ReportSuccess_Call {
	return &mockmetricsSender_ReportSuccess_Call{Call: _e.mock.On("ReportSuccess", count)}
}

func (_c *mockmetricsSender_ReportSuccess_Call) Run(run func(count int)) *mockmetricsSender_ReportSuccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockmetricsSender_ReportSuccess_Call) Return() *mockmetricsSender_ReportSuccess_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockmetricsSender_ReportSuccess_Call) RunAndReturn(run func(count int)) *mockmetricsSender_ReportSuccess_Call {
	_c.Run(run)
	return _c
}

// newMockclient creates a new instance of mockclient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockclient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockclient {
	mock := &mockclient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockclient is an autogenerated mock type for the client type
type mockclient struct {
	mock.Mock
}

type mockclient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockclient) EXPECT() *mockclient_Expecter {
	return &mockclient_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function for the type mockclient
func (_mock *mockclient) Fetch() ([]product.Product, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []product.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]product.Product, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []product.Product); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]product.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockclient_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type mockclient_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
func (_e *mockclient_Expecter) Fetch() *mockclient_Fetch_Call {
	return &mockclient_Fetch_Call{Call: _e.mock.On("Fetch")}
}

func (_c *mockclient_Fetch_Call) Run(run func()) *mockclient_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockclient_Fetch_Call) Return(products []product.Product, err error) *mockclient_Fetch_Call {
	_c.Call.Return(products, err)
	return _c
}

func (_c *mockclient_Fetch_Call) RunAndReturn(run func() ([]product.Product, error)) *mockclient_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// newMockrepository creates a new instance of mockrepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockrepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockrepository {
	mock := &mockrepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockrepository is an autogenerated mock type for the repository type
type mockrepository struct {
	mock.Mock
}

type mockrepository_Expecter struct {
	mock *mock.Mock
}

func (_m *mockrepository) EXPECT() *mockrepository_Expecter {
	return &mockrepository_Expecter{mock: &_m.Mock}
}

// FindByIDs provides a mock function for the type mockrepository
func (_mock *mockrepository) FindByIDs(productIDs []product.ID) (map[product.ID]product.Product, error) {
	ret := _mock.Called(productIDs)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDs")
	}

	var r0 map[product.ID]product.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]product.ID) (map[product.ID]product.Product, error)); ok {
		return returnFunc(productIDs)
	}
	if returnFunc, ok := ret.Get(0).(func([]product.ID) map[product.ID]product.Product); ok {
		r0 = returnFunc(productIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[product.ID]product.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]product.ID) error); ok {
		r1 = returnFunc(productIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockrepository_FindByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDs'
type mockrepository_FindByIDs_Call struct {
	*mock.Call
}

// FindByIDs is a helper method to define mock.On call
//   - productIDs []product.ID
func (_e *mockrepository_Expecter) FindByIDs(productIDs interface{}) *mockrepository_FindByIDs_Call {
	return &mockrepository_FindByIDs_Call{Call: _e.mock.On("FindByIDs", productIDs)}
}

func (_c *mockrepository_FindByIDs_Call) Run(run func(productIDs []product.ID)) *mockrepository_FindByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []product.ID
		if args[0] != nil {
			arg0 = args[0].([]product.ID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockrepository_FindByIDs_Call) Return(iDToProduct map[product.ID]product.Product, err error) *mockrepository_FindByIDs_Call {
	_c.Call.Return(iDToProduct, err)
	return _c
}

func (_c *mockrepository_FindByIDs_Call) RunAndReturn(run func(productIDs []product.ID) (map[product.ID]product.Product, error)) *mockrepository_FindByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type mockrepository
func (_mock *mockrepository) Save(products []product.Product) error {
	ret := _mock.Called(products)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]product.Product) error); ok {
		r0 = returnFunc(products)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockrepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type mockrepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - products []product.Product
func (_e *mockrepository_Expecter) Save(products interface{}) *mockrepository_Save_Call {
	return &mockrepository_Save_Call{Call: _e.mock.On("Save", products)}
}

func (_c *mockrepository_Save_Call) Run(run func(products []product.Product)) *mockrepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []product.Product
		if args[0] != nil {
			arg0 = args[0].([]product.Product)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockrepository_Save_Call) Return(err error) *mockrepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockrepository_Save_Call) RunAndReturn(run func(products []product.Product) error) *mockrepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
